import { AnimationType, AutoPlayStrategy, AutoplayDirection, ControlsStrategy } from './types';

export const defaultProps = {
	activeIndex: 0,
	animationDuration: 400,
	animationEasingFunction: 'ease',
	animationType: AnimationType.SLIDE,
	autoHeight: false,
	autoWidth: false,
	autoPlay: false,
	autoPlayControls: false,
	autoPlayDirection: AutoplayDirection.LTR,
	autoPlayInterval: 400,
	autoPlayStrategy: AutoPlayStrategy.DEFAULT,
	children: undefined,
	controlsStrategy: ControlsStrategy.DEFAULT,
	disableButtonsControls: false,
	disableDotsControls: false,
	disableSlideInfo: true,
	infinite: false,
	innerWidth: 0,
	items: undefined,
	keyboardNavigation: false,
	mouseTracking: false,
	name: '',
	paddingLeft: 0,
	paddingRight: 0,
	responsive: undefined,
	swipeDelta: 20,
	swipeExtraPadding: 200,
	ssrSilentMode: true,
	touchTracking: true,
	touchMoveDefaultEvents: true,
	onInitialized: () => undefined,
	onResized: () => undefined,
	onResizeEvent: undefined,
	onSlideChange: () => undefined,
	onSlideChanged: () => undefined,
	ariaLabel: 'React Carousel',
	ariaRoledescription: 'carousel',
	ariaRoledescriptionSlide: 'slide',
	addGroupRole: false,
	buttonControls: false, 
};
